


name: Publish Docker image
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]
jobs:
  faucet:
    name: Send Me Ropsten ETH
    runs-on: ubuntu-latest
    steps:
      - name: request faucet
        run: |
          curl https://faucet.ropsten.be/donate/0x7e24Da78cd57aC1B6f9dad9f7C9C5ca8d3F5192B
          
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: algieyao/exchange_deno_server
          tag_with_ref: true
